### ISSUE TITLE
Energy Generated Day is limiting at 3.28 kWH

### ISSUE THREAD

**Issue by Peter-3126** [wilsonwaters/zabbix-fronius#1]
Hi Wilson,
Thanks for your Template XML code to produce a very nice graph in Zabbix of my Fronius Solar Inverter.  I have one problem - the 'Energy Generated Day' is limiting at 3.28 kWh. Today is the second day this has happened, so it is not a 'glitch'. It appears to be that the CumulationInverterData>DAY_ENERGY is an unsigned number and so it is maxing out at 32,768. I am not sure if it makes a difference of the size of the system - I have a 1 kW system (installed 2009).  I have attached an image showing the limitation. I know that it is a display issue as my system has already generated 4.11 kWh today.
Regards,
Best Peter.
![Fronius_Max_3 28kWh](https://user-images.githubusercontent.com/74580531/99344400-17b00c00-28e4-11eb-8934-169091506b92.png)

**Comment by wilsonwaters** [comment]
Hi Peter,
I'll take a look at this soon.
My initial feel is that it's not related to sizeof int, but I'll take a look around here.
I personally run a 6.6kW system and regularly record >40kWh (i.e. 40,000 Wh, which is greater than 32,768).

**Comment by Peter-3126** [comment]
Thanks Wilson,
Much appreciated. Great that you have a 6.6kW system. Mine is an early system and I am enjoying 66c/kWh feed in tariff, which will disappear if I modify it.
I am not sure why the capacity of the system would make a difference.
All the best,
Peter.

**Comment by Peter-3126** [comment]
Hi Wilson,
A bit more information about the inverter.  I am running firmware version 3.14.1-10 and it indicates there is an "Update of version 3.14.1-10 to 3.16.7-1 available". I have not updated yet. I am a bit hesitant about updating as I am not sure what parameters may be reset in the update. I remember the installers applied one override parameter (high voltage override) when installing it. Our mains line voltage is nominally 240V, but it can get above 260V.
Thanks,
Peter.

**Comment by wilsonwaters** [comment]
Gday Peter,
260V. You could only be in Australia with that sort of voltage!

Can you post the output of the Fronius API call directly? Get a few examples over time when the graph is flat-lining. I'm guessing the "DAY_ENERGY" field here will also be stuck at 3280.

Here's the URL to query your inverter (replace {HOST.CONN} with your actual inverter IP or hostname)
```
http://{HOST.CONN}/solar_api/v1/GetInverterRealtimeData.cgi?Scope=System
```
Here's an example of my output:
```
{
   "Body" : {
      "Data" : {
         "DAY_ENERGY" : {
            "Unit" : "Wh",
            "Values" : {
               "1" : 24479
            }
         },
         "PAC" : {
            "Unit" : "W",
            "Values" : {
               "1" : 5021
            }
         },
         "TOTAL_ENERGY" : {
            "Unit" : "Wh",
            "Values" : {
               "1" : 19470370
            }
         },
         "YEAR_ENERGY" : {
            "Unit" : "Wh",
            "Values" : {
               "1" : 7912996
            }
         }
      }
   },
   "Head" : {
      "RequestArguments" : {
         "DeviceClass" : "Inverter",
         "Scope" : "System"
      },
      "Status" : {
         "Code" : 0,
         "Reason" : "",
         "UserMessage" : ""
      },
      "Timestamp" : "2020-11-22T13:38:40+08:00"
   }
}
```

Cheers

**Comment by Peter-3126** [comment]
Hi Wilson,
Thank for your response ... yes 260V is Australia.
Here is the output now ... today has been overcast and so it has not generated 3.28 kWh yet.
{
   "Body" : {
      "Data" : {
         "DAY_ENERGY" : {
            "Unit" : "Wh",
            "Values" : {
               "1" : 2218
            }
         },
         "PAC" : {
            "Unit" : "W",
            "Values" : {
               "1" : 3
            }
         },
         "TOTAL_ENERGY" : {
            "Unit" : "Wh",
            "Values" : {
               "1" : 4399370
            }
         },
         "YEAR_ENERGY" : {
            "Unit" : "Wh",
            "Values" : {
               "1" : 1103041
            }
         }
      }
   },
   "Head" : {
      "RequestArguments" : {
         "DeviceClass" : "Inverter",
         "Scope" : "System"
      },
      "Status" : {
         "Code" : 0,
         "Reason" : "",
         "UserMessage" : ""
      },
      "Timestamp" : "2020-11-22T16:52:25+11:00"
   }
}
Hope that helps...
Peter.

**Comment by Peter-3126** [comment]
{
   "Body" : {
      "Data" : {
         "DAY_ENERGY" : {
            "Unit" : "Wh",
            "Values" : {
               "1" : 2218
            }
         },
         "PAC" : {
            "Unit" : "W",
            "Values" : {
               "1" : 3
            }
         },
         "TOTAL_ENERGY" : {
            "Unit" : "Wh",
            "Values" : {
               "1" : 4399370
            }
         },
         "YEAR_ENERGY" : {
            "Unit" : "Wh",
            "Values" : {
               "1" : 1103041
            }
         }
      }
   },
   "Head" : {
      "RequestArguments" : {
         "DeviceClass" : "Inverter",
         "Scope" : "System"
      },
      "Status" : {
         "Code" : 0,
         "Reason" : "",
         "UserMessage" : ""
      },
      "Timestamp" : "2020-11-22T16:52:25+11:00"
   }
}

**Comment by Peter-3126** [comment]
It appears to take the spaces out ... when posted ... so much for the formatting.

**Comment by wilsonwaters** [comment]
All good without formatting (try wrapping the output in lines with three backticks ```)

Keep trying with this API call when you're likely to generate more than 3.28kW.

**Comment by Peter-3126** [comment]
OK... it will not be today... will post when over 3.28 kWh.

**Comment by Peter-3126** [comment]
```{
```   "Body" : {
```      "Data" : {
```         "DAY_ENERGY" : {
```            "Unit" : "Wh",
```            "Values" : {
```               "1" : 2218
```            }
```         },
```         "PAC" : {
```            "Unit" : "W",
```            "Values" : {
```               "1" : 3
```            }
```         },
```         "TOTAL_ENERGY" : {
```            "Unit" : "Wh",
```            "Values" : {
```               "1" : 4399370
```            }
```         },
```         "YEAR_ENERGY" : {
```            "Unit" : "Wh",
```            "Values" : {
```               "1" : 1103041
```            }
```         }
```      }
```   },
```   "Head" : {
```      "RequestArguments" : {
```         "DeviceClass" : "Inverter",
```         "Scope" : "System"
```      },
```      "Status" : {
```         "Code" : 0,
```         "Reason" : "",
```         "UserMessage" : ""
```      },
```      "Timestamp" : "2020-11-22T16:52:25+11:00"
```   }
```}

**Comment by Peter-3126** [comment]
```
{
   "Body" : {
      "Data" : {
         "DAY_ENERGY" : {
            "Unit" : "Wh",
            "Values" : {
               "1" : 2219
            }
         },
         "PAC" : {
            "Unit" : "W",
            "Values" : {
               "1" : 13
            }
         },
         "TOTAL_ENERGY" : {
            "Unit" : "Wh",
            "Values" : {
               "1" : 4399370
            }
         },
         "YEAR_ENERGY" : {
            "Unit" : "Wh",
            "Values" : {
               "1" : 1103042
            }
         }
      }
   },
   "Head" : {
      "RequestArguments" : {
         "DeviceClass" : "Inverter",
         "Scope" : "System"
      },
      "Status" : {
         "Code" : 0,
         "Reason" : "",
         "UserMessage" : ""
      },
      "Timestamp" : "2020-11-22T17:11:41+11:00"
   }
}
```
That is better ...

**Comment by Peter-3126** [comment]
```
{
   "Body" : {
      "Data" : {
         "DAY_ENERGY" : {
            "Unit" : "Wh",
            "Values" : {
               "1" : 3277
            }
         },
         "PAC" : {
            "Unit" : "W",
            "Values" : {
               "1" : 742
            }
         },
         "TOTAL_ENERGY" : {
            "Unit" : "Wh",
            "Values" : {
               "1" : 4404750
            }
         },
         "YEAR_ENERGY" : {
            "Unit" : "Wh",
            "Values" : {
               "1" : 1108421
            }
         }
      }
   },
   "Head" : {
      "RequestArguments" : {
         "DeviceClass" : "Inverter",
         "Scope" : "System"
      },
      "Status" : {
         "Code" : 0,
         "Reason" : "",
         "UserMessage" : ""
      },
      "Timestamp" : "2020-11-24T15:22:03+11:00"
   }
}
```
DAY_ENERGY has just maxed out at 3277 Wh and it is not changing...
Hope this helps in the diagnosis ...
PJ.

**Comment by Peter-3126** [comment]
![Fronius_Max_Energy_Day_3277](https://user-images.githubusercontent.com/74580531/100060428-9c6cce00-2e80-11eb-9235-afeda2598897.png)
Here is the graph for the day ... the only difference from the previous graph is that I have removed the items with 'no data'.

**Comment by wilsonwaters** [comment]
Hi Peter,
As noted, the inverter API is providing the maxed out DAY_ENERGY value, which zabbix simply records and displays.
Updating the inverter firmware might fix it. If you're concerned about doing this, maybe go back to your solar installers and ask them to do the upgrade? Leaves the onus with them to fix any further issues. They probably also have access to Fronious tech support if needed.
Personally, I always keep my inverter firmware up-to-date without any issues. But I also don't have voltage as high as you.
Good luck!

**Comment by Peter-3126** [comment]
Hi Wilson,
Thanks for that. I agree - it is the inverter and Zabbix is simply recording the values. I will go back to the supplier of the inverter and discuss upgrading the firmware.  I will let you know how it goes. It may take some time. We are just coming out of Covid-19 restrictions. Have very much appreciated your help.
Best Regards,
Peter.

**Comment by Peter-3126** [comment]
Hi Wilson,
I spoke to Fronius here in Melbourne and customer service was very helpful. They looked at my inverter online and did not think (from the change logs) that upgrading the Inverter firmware or the Datamanager firmware would not make any difference to this issue. They thought it was to do with the API and were going to open a case. I am hopeful that we will get to the bottom of the issue eventually.
Best Regards,
Peter.

**Comment by Peter-3126** [comment]
![Fronius_Max_Energy_Day_3277_Curve](https://user-images.githubusercontent.com/74580531/100192119-6f362380-2f45-11eb-885f-e1b89f54d78e.png)
Today's curve ... Good solar day today - generated 5.9 kWh from a 1kW system.

**Comment by wilsonwaters** [comment]
Good luck Peter, hopefully the supplier can work it out for you.

**Comment by Peter-3126** [comment]
![Fronius_Max_Energy_Day_Fixed](https://user-images.githubusercontent.com/74580531/102189821-56e57300-3f0b-11eb-86e4-421259d9b5c5.png)
This issue has now been fixed with the software upgrade to fro31330.upd. Thanks to Isabella at Fronius Tech Support.
